version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luuna-backend-test-backend-image
    container_name: luuna-backend-test-backend
    restart: unless-stopped
    ports:
      - '8080:8080'
